### ISSUE TITLE
Request for a preview version

### ISSUE THREAD

**Issue by whitewum** [UNSW-database/GraphDB-Benchmark#1]
The work is very intereting. 

Can I ask for a preview version?

Is it possible to download it from somewhere?

**Comment by zhengyi-yang** [comment]
Thanks for your interest. I've uploaded the preview version to this repo.

**Comment by whitewum** [comment]
BTW, will you have a presentation or post at KSEM 2020?

**Comment by zhengyi-yang** [comment]
Yep, we will have a presentation

**Comment by whitewum** [comment]
Great! See you at Hangzhou.
